"""Generate the QML-only fallback from the shared JSON theme source.

Run after editing palettes.json. --check validates the checked-in artifact.
The generated JS also supports Qt Design Studio without an AppController.
"""
import argparse
import json
from pathlib import Path


def generated_text(source: Path) -> str:
    data = json.loads(source.read_text(encoding="utf-8"))
    return ("// Generated by scripts/generate_theme_data.py; edit palettes.json instead.\n"
            ".pragma library\n\nvar data = " + json.dumps(data, indent=2) + ";\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    folder = Path(__file__).resolve().parents[1] / "src/qt_dicom_viewer/qml/theme"
    expected = generated_text(folder / "palettes.json")
    target = folder / "PaletteData.js"
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit("Theme data is stale: run python scripts/generate_theme_data.py")
    else:
        target.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
